pub mod plugin;
pub mod default_plugin;
pub mod number_plugin;
pub mod whitespace_plugin;
pub mod comment_plugin;
pub mod text_plugin;
pub mod symbol_plugin;
pub mod operator_plugin;
pub mod universe_plugin;
